name: chatbot_app
description: A simple chatbot app built with Flutter.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

  # Add other packages here if needed

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

 